#!/bin/bash
# Update src/ by copying relevant files from the `mathlib` in the `_target` folder.
cp _target/deps/mathlib/src/algebraic_number_theory/{class_number,number_field}.lean _target/deps/mathlib/src/group_theory/group_action/defs.lean _target/deps/mathlib/src/ring_theory/{class_group.lean,dedekind_domain.lean,fractional_ideal.lean,trace.lean} src/
